name: Check HTML and Links

on: [ push, pull_request ]

jobs:

  Check:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install
        gem install nokogiri
        gem install html-proofer --minimal-deps
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

    - name: Build
      run: bundle exec jekyll build

    - name: Check
      run: |
        htmlproofer ./_site --only-4xx --ignore-urls "/vimeo.com/,/twitter.com/,/arnoldrenderer.com/,/shotgridsoftware.com/"
